### ISSUE TITLE
MCS config is begin moved after system restart

### ISSUE THREAD

**Issue by niander** [Magisk-Modules-Repo/Magic-Charging-Switch#2]
MCS is saving its configuration in `PersistDir=/data/media/mcs`. However, my phone is moving this directory to `/data/media/0/mcs` when I restart it. So, when MCS loads again it does not recover the config and I have to setup everything again.

I have not idea why my phone moves this folder. I have an OnePlus 5T running on OxygenOS 5.1.3, that is Oreo 8.1.0.

I am also questioning why `PersistDir` is set up to this directory. I found it an odd choice when `/data/media/0/` is the primary and default user storage. I could be wrong here. Thank you.

**Comment by VR-25** [comment]
Thats really odd. A new build is coming. Let me know how things go when it becomes available.
Regarding the other subject, /data/media is safer than /data/media/0. The module used to store its data there, but I found that location unreliable. It's not always guaranteed to be available early enough for mcs to use it.

**Comment by niander** [comment]
The problem has been solved. I believe it was an OS issue. Not a MCS problem. Thank you
