### ISSUE TITLE
can't install with magisk 16.6

### ISSUE THREAD

**Issue by Spoil001** [Magisk-Modules-Repo/Magic-Charging-Switch#3]
log:

- Copying zip to temp directory
- Installing Magic_Charging_Switch_(mcs)-2018.3.6.zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
  inflating: common/config/macrodroid
  inflating: common/config/mcs
  inflating: common/config/switches
  inflating: common/config/tasker
  inflating: common/service.sh
  inflating: module.prop
(!) Magisk mount point not found
Failed!
! Installation failed

**Comment by Younes-L** [comment]
Issue still present as of Magisk 16.7
The mount point location needs to be updated , that is as far as I can tell.

**Comment by VR-25** [comment]
Fixed!
