### ISSUE TITLE
Battery stats reset error with new update (2018.8.1)

### ISSUE THREAD

**Issue by niander** [Magisk-Modules-Repo/Magic-Charging-Switch#4]
With the new update (2018.8.1) `dumpsys` command is not being found when executing `mcs -d`. I am getting the following error: `/system/xbin/mcs[792]: dumpsys: not found`
However, if I open a terminal I am able to execute `dumpsys batterystats --reset`. The command is found at `system/bin/dumpsys` but since the latest update the script is not finding `dumpsys` in the path.

**Comment by VR-25** [comment]
Fixed, thanks.
